# Generated by Django 4.2 on 2023-05-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoreUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.TextField()),
                ('user_name', models.TextField()),
                ('user_level', models.IntegerField()),
                ('login_status', models.TextField()),
                ('is_banned', models.IntegerField()),
                ('is_delete', models.IntegerField()),
                ('is_approved', models.IntegerField()),
            ],
            options={
                'db_table': 'estore_user',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'estore_message',
            },
        ),
    ]
